remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Joao Paulo Almeida de Mendonca
logo: /assets/img/profile.png
description: Very verbouse description of my website, to see where it will apear. 
show_downloads: false

