remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: João Paulo Almeida de Mendonça
logo: profile.png
description: Research Engineer, Laboratoire SIMaP
Universite Grenoble Alpes, France 
show_downloads: false

